services:

  app:
    build: .
    ports:
      - "8080:8080"       
    depends_on: 
      - db
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/mydb

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
       - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports: 
      - "80:80"
    depends_on:
      - app

volumes:
  db_data:
